services:
  web:
    build: .
    expose:
      - 80
    environment:
      - PORT=80
      - APP_PASSWORD=secret123
      - FLASK_SECRET_KEY=supersecretkeyCHANGE_ME
      - REQUIRE_LOGIN=true
    volumes:
      - .:/app
